// Code generated by MockGen. DO NOT EDIT.
// Source: clickyab.com/crane/crane/entity (interfaces: Context,Advertise,Campaign,Publisher,Location,Seat,Supplier,Request)

package mock_entity

import (
	entity "clickyab.com/crane/crane/entity"
	gomock "github.com/golang/mock/gomock"
	net "net"
	time "time"
)

// MockContext is a mock of Context interface
type MockContext struct {
	ctrl     *gomock.Controller
	recorder *MockContextMockRecorder
}

// MockContextMockRecorder is the mock recorder for MockContext
type MockContextMockRecorder struct {
	mock *MockContext
}

// NewMockContext creates a new mock instance
func NewMockContext(ctrl *gomock.Controller) *MockContext {
	mock := &MockContext{ctrl: ctrl}
	mock.recorder = &MockContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockContext) EXPECT() *MockContextMockRecorder {
	return _m.recorder
}

// Alexa mocks base method
func (_m *MockContext) Alexa() bool {
	ret := _m.ctrl.Call(_m, "Alexa")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Alexa indicates an expected call of Alexa
func (_mr *MockContextMockRecorder) Alexa() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Alexa")
}

// Capping mocks base method
func (_m *MockContext) Capping() bool {
	ret := _m.ctrl.Call(_m, "Capping")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Capping indicates an expected call of Capping
func (_mr *MockContextMockRecorder) Capping() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Capping")
}

// Category mocks base method
func (_m *MockContext) Category() []entity.Category {
	ret := _m.ctrl.Call(_m, "Category")
	ret0, _ := ret[0].([]entity.Category)
	return ret0
}

// Category indicates an expected call of Category
func (_mr *MockContextMockRecorder) Category() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Category")
}

// Currency mocks base method
func (_m *MockContext) Currency() string {
	ret := _m.ctrl.Call(_m, "Currency")
	ret0, _ := ret[0].(string)
	return ret0
}

// Currency indicates an expected call of Currency
func (_mr *MockContextMockRecorder) Currency() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Currency")
}

// EventPage mocks base method
func (_m *MockContext) EventPage() string {
	ret := _m.ctrl.Call(_m, "EventPage")
	ret0, _ := ret[0].(string)
	return ret0
}

// EventPage indicates an expected call of EventPage
func (_mr *MockContextMockRecorder) EventPage() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "EventPage")
}

// FloorDiv mocks base method
func (_m *MockContext) FloorDiv() int64 {
	ret := _m.ctrl.Call(_m, "FloorDiv")
	ret0, _ := ret[0].(int64)
	return ret0
}

// FloorDiv indicates an expected call of FloorDiv
func (_mr *MockContextMockRecorder) FloorDiv() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FloorDiv")
}

// IP mocks base method
func (_m *MockContext) IP() net.IP {
	ret := _m.ctrl.Call(_m, "IP")
	ret0, _ := ret[0].(net.IP)
	return ret0
}

// IP indicates an expected call of IP
func (_mr *MockContextMockRecorder) IP() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "IP")
}

// IsMobile mocks base method
func (_m *MockContext) IsMobile() bool {
	ret := _m.ctrl.Call(_m, "IsMobile")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsMobile indicates an expected call of IsMobile
func (_mr *MockContextMockRecorder) IsMobile() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "IsMobile")
}

// Location mocks base method
func (_m *MockContext) Location() entity.Location {
	ret := _m.ctrl.Call(_m, "Location")
	ret0, _ := ret[0].(entity.Location)
	return ret0
}

// Location indicates an expected call of Location
func (_mr *MockContextMockRecorder) Location() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Location")
}

// MultiVideo mocks base method
func (_m *MockContext) MultiVideo() bool {
	ret := _m.ctrl.Call(_m, "MultiVideo")
	ret0, _ := ret[0].(bool)
	return ret0
}

// MultiVideo indicates an expected call of MultiVideo
func (_mr *MockContextMockRecorder) MultiVideo() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "MultiVideo")
}

// OS mocks base method
func (_m *MockContext) OS() entity.OS {
	ret := _m.ctrl.Call(_m, "OS")
	ret0, _ := ret[0].(entity.OS)
	return ret0
}

// OS indicates an expected call of OS
func (_mr *MockContextMockRecorder) OS() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "OS")
}

// Parent mocks base method
func (_m *MockContext) Parent() string {
	ret := _m.ctrl.Call(_m, "Parent")
	ret0, _ := ret[0].(string)
	return ret0
}

// Parent indicates an expected call of Parent
func (_mr *MockContextMockRecorder) Parent() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Parent")
}

// Protocol mocks base method
func (_m *MockContext) Protocol() entity.Protocol {
	ret := _m.ctrl.Call(_m, "Protocol")
	ret0, _ := ret[0].(entity.Protocol)
	return ret0
}

// Protocol indicates an expected call of Protocol
func (_mr *MockContextMockRecorder) Protocol() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Protocol")
}

// Publisher mocks base method
func (_m *MockContext) Publisher() entity.Publisher {
	ret := _m.ctrl.Call(_m, "Publisher")
	ret0, _ := ret[0].(entity.Publisher)
	return ret0
}

// Publisher indicates an expected call of Publisher
func (_mr *MockContextMockRecorder) Publisher() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Publisher")
}

// Referrer mocks base method
func (_m *MockContext) Referrer() string {
	ret := _m.ctrl.Call(_m, "Referrer")
	ret0, _ := ret[0].(string)
	return ret0
}

// Referrer indicates an expected call of Referrer
func (_mr *MockContextMockRecorder) Referrer() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Referrer")
}

// Seats mocks base method
func (_m *MockContext) Seats() []entity.Seat {
	ret := _m.ctrl.Call(_m, "Seats")
	ret0, _ := ret[0].([]entity.Seat)
	return ret0
}

// Seats indicates an expected call of Seats
func (_mr *MockContextMockRecorder) Seats() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Seats")
}

// Suspicious mocks base method
func (_m *MockContext) Suspicious() int {
	ret := _m.ctrl.Call(_m, "Suspicious")
	ret0, _ := ret[0].(int)
	return ret0
}

// Suspicious indicates an expected call of Suspicious
func (_mr *MockContextMockRecorder) Suspicious() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Suspicious")
}

// Timestamp mocks base method
func (_m *MockContext) Timestamp() time.Time {
	ret := _m.ctrl.Call(_m, "Timestamp")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Timestamp indicates an expected call of Timestamp
func (_mr *MockContextMockRecorder) Timestamp() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Timestamp")
}

// Tiny mocks base method
func (_m *MockContext) Tiny() bool {
	ret := _m.ctrl.Call(_m, "Tiny")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Tiny indicates an expected call of Tiny
func (_mr *MockContextMockRecorder) Tiny() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Tiny")
}

// Type mocks base method
func (_m *MockContext) Type() entity.RequestType {
	ret := _m.ctrl.Call(_m, "Type")
	ret0, _ := ret[0].(entity.RequestType)
	return ret0
}

// Type indicates an expected call of Type
func (_mr *MockContextMockRecorder) Type() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Type")
}

// User mocks base method
func (_m *MockContext) User() entity.User {
	ret := _m.ctrl.Call(_m, "User")
	ret0, _ := ret[0].(entity.User)
	return ret0
}

// User indicates an expected call of User
func (_mr *MockContextMockRecorder) User() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "User")
}

// UserAgent mocks base method
func (_m *MockContext) UserAgent() string {
	ret := _m.ctrl.Call(_m, "UserAgent")
	ret0, _ := ret[0].(string)
	return ret0
}

// UserAgent indicates an expected call of UserAgent
func (_mr *MockContextMockRecorder) UserAgent() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UserAgent")
}

// MockAdvertise is a mock of Advertise interface
type MockAdvertise struct {
	ctrl     *gomock.Controller
	recorder *MockAdvertiseMockRecorder
}

// MockAdvertiseMockRecorder is the mock recorder for MockAdvertise
type MockAdvertiseMockRecorder struct {
	mock *MockAdvertise
}

// NewMockAdvertise creates a new mock instance
func NewMockAdvertise(ctrl *gomock.Controller) *MockAdvertise {
	mock := &MockAdvertise{ctrl: ctrl}
	mock.recorder = &MockAdvertiseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockAdvertise) EXPECT() *MockAdvertiseMockRecorder {
	return _m.recorder
}

// AdCTR mocks base method
func (_m *MockAdvertise) AdCTR() float64 {
	ret := _m.ctrl.Call(_m, "AdCTR")
	ret0, _ := ret[0].(float64)
	return ret0
}

// AdCTR indicates an expected call of AdCTR
func (_mr *MockAdvertiseMockRecorder) AdCTR() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AdCTR")
}

// AdTarget mocks base method
func (_m *MockAdvertise) AdTarget() string {
	ret := _m.ctrl.Call(_m, "AdTarget")
	ret0, _ := ret[0].(string)
	return ret0
}

// AdTarget indicates an expected call of AdTarget
func (_mr *MockAdvertiseMockRecorder) AdTarget() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AdTarget")
}

// Attributes mocks base method
func (_m *MockAdvertise) Attributes() map[string]interface{} {
	ret := _m.ctrl.Call(_m, "Attributes")
	ret0, _ := ret[0].(map[string]interface{})
	return ret0
}

// Attributes indicates an expected call of Attributes
func (_mr *MockAdvertiseMockRecorder) Attributes() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Attributes")
}

// Campaign mocks base method
func (_m *MockAdvertise) Campaign() entity.Campaign {
	ret := _m.ctrl.Call(_m, "Campaign")
	ret0, _ := ret[0].(entity.Campaign)
	return ret0
}

// Campaign indicates an expected call of Campaign
func (_mr *MockAdvertiseMockRecorder) Campaign() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Campaign")
}

// Capping mocks base method
func (_m *MockAdvertise) Capping() entity.Capping {
	ret := _m.ctrl.Call(_m, "Capping")
	ret0, _ := ret[0].(entity.Capping)
	return ret0
}

// Capping indicates an expected call of Capping
func (_mr *MockAdvertiseMockRecorder) Capping() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Capping")
}

// Height mocks base method
func (_m *MockAdvertise) Height() int {
	ret := _m.ctrl.Call(_m, "Height")
	ret0, _ := ret[0].(int)
	return ret0
}

// Height indicates an expected call of Height
func (_mr *MockAdvertiseMockRecorder) Height() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Height")
}

// ID mocks base method
func (_m *MockAdvertise) ID() int64 {
	ret := _m.ctrl.Call(_m, "ID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// ID indicates an expected call of ID
func (_mr *MockAdvertiseMockRecorder) ID() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ID")
}

// Media mocks base method
func (_m *MockAdvertise) Media() string {
	ret := _m.ctrl.Call(_m, "Media")
	ret0, _ := ret[0].(string)
	return ret0
}

// Media indicates an expected call of Media
func (_mr *MockAdvertiseMockRecorder) Media() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Media")
}

// SetCapping mocks base method
func (_m *MockAdvertise) SetCapping(_param0 entity.Capping) {
	_m.ctrl.Call(_m, "SetCapping", _param0)
}

// SetCapping indicates an expected call of SetCapping
func (_mr *MockAdvertiseMockRecorder) SetCapping(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetCapping", arg0)
}

// Size mocks base method
func (_m *MockAdvertise) Size() int {
	ret := _m.ctrl.Call(_m, "Size")
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size
func (_mr *MockAdvertiseMockRecorder) Size() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Size")
}

// Type mocks base method
func (_m *MockAdvertise) Type() entity.AdType {
	ret := _m.ctrl.Call(_m, "Type")
	ret0, _ := ret[0].(entity.AdType)
	return ret0
}

// Type indicates an expected call of Type
func (_mr *MockAdvertiseMockRecorder) Type() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Type")
}

// Width mocks base method
func (_m *MockAdvertise) Width() int {
	ret := _m.ctrl.Call(_m, "Width")
	ret0, _ := ret[0].(int)
	return ret0
}

// Width indicates an expected call of Width
func (_mr *MockAdvertiseMockRecorder) Width() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Width")
}

// MockCampaign is a mock of Campaign interface
type MockCampaign struct {
	ctrl     *gomock.Controller
	recorder *MockCampaignMockRecorder
}

// MockCampaignMockRecorder is the mock recorder for MockCampaign
type MockCampaignMockRecorder struct {
	mock *MockCampaign
}

// NewMockCampaign creates a new mock instance
func NewMockCampaign(ctrl *gomock.Controller) *MockCampaign {
	mock := &MockCampaign{ctrl: ctrl}
	mock.recorder = &MockCampaignMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockCampaign) EXPECT() *MockCampaignMockRecorder {
	return _m.recorder
}

// AllowedOS mocks base method
func (_m *MockCampaign) AllowedOS() []string {
	ret := _m.ctrl.Call(_m, "AllowedOS")
	ret0, _ := ret[0].([]string)
	return ret0
}

// AllowedOS indicates an expected call of AllowedOS
func (_mr *MockCampaignMockRecorder) AllowedOS() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AllowedOS")
}

// AppBrands mocks base method
func (_m *MockCampaign) AppBrands() []string {
	ret := _m.ctrl.Call(_m, "AppBrands")
	ret0, _ := ret[0].([]string)
	return ret0
}

// AppBrands indicates an expected call of AppBrands
func (_mr *MockCampaignMockRecorder) AppBrands() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AppBrands")
}

// AppCarriers mocks base method
func (_m *MockCampaign) AppCarriers() []string {
	ret := _m.ctrl.Call(_m, "AppCarriers")
	ret0, _ := ret[0].([]string)
	return ret0
}

// AppCarriers indicates an expected call of AppCarriers
func (_mr *MockCampaignMockRecorder) AppCarriers() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AppCarriers")
}

// BlackListPublisher mocks base method
func (_m *MockCampaign) BlackListPublisher() []string {
	ret := _m.ctrl.Call(_m, "BlackListPublisher")
	ret0, _ := ret[0].([]string)
	return ret0
}

// BlackListPublisher indicates an expected call of BlackListPublisher
func (_mr *MockCampaignMockRecorder) BlackListPublisher() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "BlackListPublisher")
}

// Category mocks base method
func (_m *MockCampaign) Category() []entity.Category {
	ret := _m.ctrl.Call(_m, "Category")
	ret0, _ := ret[0].([]entity.Category)
	return ret0
}

// Category indicates an expected call of Category
func (_mr *MockCampaignMockRecorder) Category() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Category")
}

// Country mocks base method
func (_m *MockCampaign) Country() []string {
	ret := _m.ctrl.Call(_m, "Country")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Country indicates an expected call of Country
func (_mr *MockCampaignMockRecorder) Country() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Country")
}

// Frequency mocks base method
func (_m *MockCampaign) Frequency() int {
	ret := _m.ctrl.Call(_m, "Frequency")
	ret0, _ := ret[0].(int)
	return ret0
}

// Frequency indicates an expected call of Frequency
func (_mr *MockCampaignMockRecorder) Frequency() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Frequency")
}

// Hoods mocks base method
func (_m *MockCampaign) Hoods() []string {
	ret := _m.ctrl.Call(_m, "Hoods")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Hoods indicates an expected call of Hoods
func (_mr *MockCampaignMockRecorder) Hoods() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Hoods")
}

// ID mocks base method
func (_m *MockCampaign) ID() int64 {
	ret := _m.ctrl.Call(_m, "ID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// ID indicates an expected call of ID
func (_mr *MockCampaignMockRecorder) ID() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ID")
}

// ISP mocks base method
func (_m *MockCampaign) ISP() []string {
	ret := _m.ctrl.Call(_m, "ISP")
	ret0, _ := ret[0].([]string)
	return ret0
}

// ISP indicates an expected call of ISP
func (_mr *MockCampaignMockRecorder) ISP() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ISP")
}

// LatLon mocks base method
func (_m *MockCampaign) LatLon() (float64, float64, float64) {
	ret := _m.ctrl.Call(_m, "LatLon")
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(float64)
	return ret0, ret1, ret2
}

// LatLon indicates an expected call of LatLon
func (_mr *MockCampaignMockRecorder) LatLon() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "LatLon")
}

// MaxBID mocks base method
func (_m *MockCampaign) MaxBID() int64 {
	ret := _m.ctrl.Call(_m, "MaxBID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// MaxBID indicates an expected call of MaxBID
func (_mr *MockCampaignMockRecorder) MaxBID() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "MaxBID")
}

// Name mocks base method
func (_m *MockCampaign) Name() string {
	ret := _m.ctrl.Call(_m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name
func (_mr *MockCampaignMockRecorder) Name() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Name")
}

// NetProvider mocks base method
func (_m *MockCampaign) NetProvider() []string {
	ret := _m.ctrl.Call(_m, "NetProvider")
	ret0, _ := ret[0].([]string)
	return ret0
}

// NetProvider indicates an expected call of NetProvider
func (_mr *MockCampaignMockRecorder) NetProvider() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "NetProvider")
}

// Province mocks base method
func (_m *MockCampaign) Province() []string {
	ret := _m.ctrl.Call(_m, "Province")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Province indicates an expected call of Province
func (_mr *MockCampaignMockRecorder) Province() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Province")
}

// Target mocks base method
func (_m *MockCampaign) Target() entity.Target {
	ret := _m.ctrl.Call(_m, "Target")
	ret0, _ := ret[0].(entity.Target)
	return ret0
}

// Target indicates an expected call of Target
func (_mr *MockCampaignMockRecorder) Target() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Target")
}

// Web mocks base method
func (_m *MockCampaign) Web() bool {
	ret := _m.ctrl.Call(_m, "Web")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Web indicates an expected call of Web
func (_mr *MockCampaignMockRecorder) Web() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Web")
}

// WebMobile mocks base method
func (_m *MockCampaign) WebMobile() bool {
	ret := _m.ctrl.Call(_m, "WebMobile")
	ret0, _ := ret[0].(bool)
	return ret0
}

// WebMobile indicates an expected call of WebMobile
func (_mr *MockCampaignMockRecorder) WebMobile() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "WebMobile")
}

// WhiteListPublisher mocks base method
func (_m *MockCampaign) WhiteListPublisher() []string {
	ret := _m.ctrl.Call(_m, "WhiteListPublisher")
	ret0, _ := ret[0].([]string)
	return ret0
}

// WhiteListPublisher indicates an expected call of WhiteListPublisher
func (_mr *MockCampaignMockRecorder) WhiteListPublisher() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "WhiteListPublisher")
}

// MockPublisher is a mock of Publisher interface
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return _m.recorder
}

// BIDType mocks base method
func (_m *MockPublisher) BIDType() entity.BIDType {
	ret := _m.ctrl.Call(_m, "BIDType")
	ret0, _ := ret[0].(entity.BIDType)
	return ret0
}

// BIDType indicates an expected call of BIDType
func (_mr *MockPublisherMockRecorder) BIDType() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "BIDType")
}

// CTR mocks base method
func (_m *MockPublisher) CTR(_param0 int) float64 {
	ret := _m.ctrl.Call(_m, "CTR", _param0)
	ret0, _ := ret[0].(float64)
	return ret0
}

// CTR indicates an expected call of CTR
func (_mr *MockPublisherMockRecorder) CTR(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CTR", arg0)
}

// FloorCPM mocks base method
func (_m *MockPublisher) FloorCPM() int64 {
	ret := _m.ctrl.Call(_m, "FloorCPM")
	ret0, _ := ret[0].(int64)
	return ret0
}

// FloorCPM indicates an expected call of FloorCPM
func (_mr *MockPublisherMockRecorder) FloorCPM() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FloorCPM")
}

// ID mocks base method
func (_m *MockPublisher) ID() int64 {
	ret := _m.ctrl.Call(_m, "ID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// ID indicates an expected call of ID
func (_mr *MockPublisherMockRecorder) ID() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ID")
}

// MinBid mocks base method
func (_m *MockPublisher) MinBid() int64 {
	ret := _m.ctrl.Call(_m, "MinBid")
	ret0, _ := ret[0].(int64)
	return ret0
}

// MinBid indicates an expected call of MinBid
func (_mr *MockPublisherMockRecorder) MinBid() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "MinBid")
}

// Name mocks base method
func (_m *MockPublisher) Name() string {
	ret := _m.ctrl.Call(_m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name
func (_mr *MockPublisherMockRecorder) Name() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Name")
}

// SoftFloorCPM mocks base method
func (_m *MockPublisher) SoftFloorCPM() int64 {
	ret := _m.ctrl.Call(_m, "SoftFloorCPM")
	ret0, _ := ret[0].(int64)
	return ret0
}

// SoftFloorCPM indicates an expected call of SoftFloorCPM
func (_mr *MockPublisherMockRecorder) SoftFloorCPM() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SoftFloorCPM")
}

// Supplier mocks base method
func (_m *MockPublisher) Supplier() entity.Supplier {
	ret := _m.ctrl.Call(_m, "Supplier")
	ret0, _ := ret[0].(entity.Supplier)
	return ret0
}

// Supplier indicates an expected call of Supplier
func (_mr *MockPublisherMockRecorder) Supplier() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Supplier")
}

// MockLocation is a mock of Location interface
type MockLocation struct {
	ctrl     *gomock.Controller
	recorder *MockLocationMockRecorder
}

// MockLocationMockRecorder is the mock recorder for MockLocation
type MockLocationMockRecorder struct {
	mock *MockLocation
}

// NewMockLocation creates a new mock instance
func NewMockLocation(ctrl *gomock.Controller) *MockLocation {
	mock := &MockLocation{ctrl: ctrl}
	mock.recorder = &MockLocationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockLocation) EXPECT() *MockLocationMockRecorder {
	return _m.recorder
}

// Country mocks base method
func (_m *MockLocation) Country() entity.Country {
	ret := _m.ctrl.Call(_m, "Country")
	ret0, _ := ret[0].(entity.Country)
	return ret0
}

// Country indicates an expected call of Country
func (_mr *MockLocationMockRecorder) Country() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Country")
}

// ISP mocks base method
func (_m *MockLocation) ISP() entity.ISP {
	ret := _m.ctrl.Call(_m, "ISP")
	ret0, _ := ret[0].(entity.ISP)
	return ret0
}

// ISP indicates an expected call of ISP
func (_mr *MockLocationMockRecorder) ISP() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ISP")
}

// LatLon mocks base method
func (_m *MockLocation) LatLon() entity.LatLon {
	ret := _m.ctrl.Call(_m, "LatLon")
	ret0, _ := ret[0].(entity.LatLon)
	return ret0
}

// LatLon indicates an expected call of LatLon
func (_mr *MockLocationMockRecorder) LatLon() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "LatLon")
}

// Province mocks base method
func (_m *MockLocation) Province() entity.Province {
	ret := _m.ctrl.Call(_m, "Province")
	ret0, _ := ret[0].(entity.Province)
	return ret0
}

// Province indicates an expected call of Province
func (_mr *MockLocationMockRecorder) Province() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Province")
}

// MockSeat is a mock of Seat interface
type MockSeat struct {
	ctrl     *gomock.Controller
	recorder *MockSeatMockRecorder
}

// MockSeatMockRecorder is the mock recorder for MockSeat
type MockSeatMockRecorder struct {
	mock *MockSeat
}

// NewMockSeat creates a new mock instance
func NewMockSeat(ctrl *gomock.Controller) *MockSeat {
	mock := &MockSeat{ctrl: ctrl}
	mock.recorder = &MockSeatMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockSeat) EXPECT() *MockSeatMockRecorder {
	return _m.recorder
}

// Bid mocks base method
func (_m *MockSeat) Bid() float64 {
	ret := _m.ctrl.Call(_m, "Bid")
	ret0, _ := ret[0].(float64)
	return ret0
}

// Bid indicates an expected call of Bid
func (_mr *MockSeatMockRecorder) Bid() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Bid")
}

// CTR mocks base method
func (_m *MockSeat) CTR() float64 {
	ret := _m.ctrl.Call(_m, "CTR")
	ret0, _ := ret[0].(float64)
	return ret0
}

// CTR indicates an expected call of CTR
func (_mr *MockSeatMockRecorder) CTR() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CTR")
}

// ClickURL mocks base method
func (_m *MockSeat) ClickURL() string {
	ret := _m.ctrl.Call(_m, "ClickURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// ClickURL indicates an expected call of ClickURL
func (_mr *MockSeatMockRecorder) ClickURL() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ClickURL")
}

// Height mocks base method
func (_m *MockSeat) Height() int {
	ret := _m.ctrl.Call(_m, "Height")
	ret0, _ := ret[0].(int)
	return ret0
}

// Height indicates an expected call of Height
func (_mr *MockSeatMockRecorder) Height() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Height")
}

// PublicID mocks base method
func (_m *MockSeat) PublicID() string {
	ret := _m.ctrl.Call(_m, "PublicID")
	ret0, _ := ret[0].(string)
	return ret0
}

// PublicID indicates an expected call of PublicID
func (_mr *MockSeatMockRecorder) PublicID() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PublicID")
}

// ReservedHash mocks base method
func (_m *MockSeat) ReservedHash() string {
	ret := _m.ctrl.Call(_m, "ReservedHash")
	ret0, _ := ret[0].(string)
	return ret0
}

// ReservedHash indicates an expected call of ReservedHash
func (_mr *MockSeatMockRecorder) ReservedHash() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ReservedHash")
}

// SetWinnerAdvertise mocks base method
func (_m *MockSeat) SetWinnerAdvertise(_param0 entity.Advertise, _param1 float64) {
	_m.ctrl.Call(_m, "SetWinnerAdvertise", _param0, _param1)
}

// SetWinnerAdvertise indicates an expected call of SetWinnerAdvertise
func (_mr *MockSeatMockRecorder) SetWinnerAdvertise(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetWinnerAdvertise", arg0, arg1)
}

// ShowT mocks base method
func (_m *MockSeat) ShowT() bool {
	ret := _m.ctrl.Call(_m, "ShowT")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShowT indicates an expected call of ShowT
func (_mr *MockSeatMockRecorder) ShowT() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ShowT")
}

// ShowURL mocks base method
func (_m *MockSeat) ShowURL() string {
	ret := _m.ctrl.Call(_m, "ShowURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// ShowURL indicates an expected call of ShowURL
func (_mr *MockSeatMockRecorder) ShowURL() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ShowURL")
}

// Size mocks base method
func (_m *MockSeat) Size() int {
	ret := _m.ctrl.Call(_m, "Size")
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size
func (_mr *MockSeatMockRecorder) Size() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Size")
}

// Type mocks base method
func (_m *MockSeat) Type() string {
	ret := _m.ctrl.Call(_m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type
func (_mr *MockSeatMockRecorder) Type() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Type")
}

// Width mocks base method
func (_m *MockSeat) Width() int {
	ret := _m.ctrl.Call(_m, "Width")
	ret0, _ := ret[0].(int)
	return ret0
}

// Width indicates an expected call of Width
func (_mr *MockSeatMockRecorder) Width() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Width")
}

// WinnerAdvertise mocks base method
func (_m *MockSeat) WinnerAdvertise() entity.Advertise {
	ret := _m.ctrl.Call(_m, "WinnerAdvertise")
	ret0, _ := ret[0].(entity.Advertise)
	return ret0
}

// WinnerAdvertise indicates an expected call of WinnerAdvertise
func (_mr *MockSeatMockRecorder) WinnerAdvertise() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "WinnerAdvertise")
}

// MockSupplier is a mock of Supplier interface
type MockSupplier struct {
	ctrl     *gomock.Controller
	recorder *MockSupplierMockRecorder
}

// MockSupplierMockRecorder is the mock recorder for MockSupplier
type MockSupplierMockRecorder struct {
	mock *MockSupplier
}

// NewMockSupplier creates a new mock instance
func NewMockSupplier(ctrl *gomock.Controller) *MockSupplier {
	mock := &MockSupplier{ctrl: ctrl}
	mock.recorder = &MockSupplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockSupplier) EXPECT() *MockSupplierMockRecorder {
	return _m.recorder
}

// AllowCreate mocks base method
func (_m *MockSupplier) AllowCreate() bool {
	ret := _m.ctrl.Call(_m, "AllowCreate")
	ret0, _ := ret[0].(bool)
	return ret0
}

// AllowCreate indicates an expected call of AllowCreate
func (_mr *MockSupplierMockRecorder) AllowCreate() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AllowCreate")
}

// BidType mocks base method
func (_m *MockSupplier) BidType() entity.BIDType {
	ret := _m.ctrl.Call(_m, "BidType")
	ret0, _ := ret[0].(entity.BIDType)
	return ret0
}

// BidType indicates an expected call of BidType
func (_mr *MockSupplierMockRecorder) BidType() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "BidType")
}

// DefaultCTR mocks base method
func (_m *MockSupplier) DefaultCTR() float64 {
	ret := _m.ctrl.Call(_m, "DefaultCTR")
	ret0, _ := ret[0].(float64)
	return ret0
}

// DefaultCTR indicates an expected call of DefaultCTR
func (_mr *MockSupplierMockRecorder) DefaultCTR() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DefaultCTR")
}

// DefaultFloorCPM mocks base method
func (_m *MockSupplier) DefaultFloorCPM() int64 {
	ret := _m.ctrl.Call(_m, "DefaultFloorCPM")
	ret0, _ := ret[0].(int64)
	return ret0
}

// DefaultFloorCPM indicates an expected call of DefaultFloorCPM
func (_mr *MockSupplierMockRecorder) DefaultFloorCPM() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DefaultFloorCPM")
}

// DefaultMinBid mocks base method
func (_m *MockSupplier) DefaultMinBid() int64 {
	ret := _m.ctrl.Call(_m, "DefaultMinBid")
	ret0, _ := ret[0].(int64)
	return ret0
}

// DefaultMinBid indicates an expected call of DefaultMinBid
func (_mr *MockSupplierMockRecorder) DefaultMinBid() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DefaultMinBid")
}

// DefaultSoftFloorCPM mocks base method
func (_m *MockSupplier) DefaultSoftFloorCPM() int64 {
	ret := _m.ctrl.Call(_m, "DefaultSoftFloorCPM")
	ret0, _ := ret[0].(int64)
	return ret0
}

// DefaultSoftFloorCPM indicates an expected call of DefaultSoftFloorCPM
func (_mr *MockSupplierMockRecorder) DefaultSoftFloorCPM() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DefaultSoftFloorCPM")
}

// Name mocks base method
func (_m *MockSupplier) Name() string {
	ret := _m.ctrl.Call(_m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name
func (_mr *MockSupplierMockRecorder) Name() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Name")
}

// TinyMark mocks base method
func (_m *MockSupplier) TinyMark() bool {
	ret := _m.ctrl.Call(_m, "TinyMark")
	ret0, _ := ret[0].(bool)
	return ret0
}

// TinyMark indicates an expected call of TinyMark
func (_mr *MockSupplierMockRecorder) TinyMark() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "TinyMark")
}

// Token mocks base method
func (_m *MockSupplier) Token() string {
	ret := _m.ctrl.Call(_m, "Token")
	ret0, _ := ret[0].(string)
	return ret0
}

// Token indicates an expected call of Token
func (_mr *MockSupplierMockRecorder) Token() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Token")
}

// MockRequest is a mock of Request interface
type MockRequest struct {
	ctrl     *gomock.Controller
	recorder *MockRequestMockRecorder
}

// MockRequestMockRecorder is the mock recorder for MockRequest
type MockRequestMockRecorder struct {
	mock *MockRequest
}

// NewMockRequest creates a new mock instance
func NewMockRequest(ctrl *gomock.Controller) *MockRequest {
	mock := &MockRequest{ctrl: ctrl}
	mock.recorder = &MockRequestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockRequest) EXPECT() *MockRequestMockRecorder {
	return _m.recorder
}

// Alexa mocks base method
func (_m *MockRequest) Alexa() bool {
	ret := _m.ctrl.Call(_m, "Alexa")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Alexa indicates an expected call of Alexa
func (_mr *MockRequestMockRecorder) Alexa() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Alexa")
}

// EventPage mocks base method
func (_m *MockRequest) EventPage() string {
	ret := _m.ctrl.Call(_m, "EventPage")
	ret0, _ := ret[0].(string)
	return ret0
}

// EventPage indicates an expected call of EventPage
func (_mr *MockRequestMockRecorder) EventPage() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "EventPage")
}

// IP mocks base method
func (_m *MockRequest) IP() net.IP {
	ret := _m.ctrl.Call(_m, "IP")
	ret0, _ := ret[0].(net.IP)
	return ret0
}

// IP indicates an expected call of IP
func (_mr *MockRequestMockRecorder) IP() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "IP")
}

// IsMobile mocks base method
func (_m *MockRequest) IsMobile() bool {
	ret := _m.ctrl.Call(_m, "IsMobile")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsMobile indicates an expected call of IsMobile
func (_mr *MockRequestMockRecorder) IsMobile() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "IsMobile")
}

// Location mocks base method
func (_m *MockRequest) Location() entity.Location {
	ret := _m.ctrl.Call(_m, "Location")
	ret0, _ := ret[0].(entity.Location)
	return ret0
}

// Location indicates an expected call of Location
func (_mr *MockRequestMockRecorder) Location() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Location")
}

// OS mocks base method
func (_m *MockRequest) OS() entity.OS {
	ret := _m.ctrl.Call(_m, "OS")
	ret0, _ := ret[0].(entity.OS)
	return ret0
}

// OS indicates an expected call of OS
func (_mr *MockRequestMockRecorder) OS() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "OS")
}

// Parent mocks base method
func (_m *MockRequest) Parent() string {
	ret := _m.ctrl.Call(_m, "Parent")
	ret0, _ := ret[0].(string)
	return ret0
}

// Parent indicates an expected call of Parent
func (_mr *MockRequestMockRecorder) Parent() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Parent")
}

// Protocol mocks base method
func (_m *MockRequest) Protocol() entity.Protocol {
	ret := _m.ctrl.Call(_m, "Protocol")
	ret0, _ := ret[0].(entity.Protocol)
	return ret0
}

// Protocol indicates an expected call of Protocol
func (_mr *MockRequestMockRecorder) Protocol() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Protocol")
}

// Referrer mocks base method
func (_m *MockRequest) Referrer() string {
	ret := _m.ctrl.Call(_m, "Referrer")
	ret0, _ := ret[0].(string)
	return ret0
}

// Referrer indicates an expected call of Referrer
func (_mr *MockRequestMockRecorder) Referrer() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Referrer")
}

// Suspicious mocks base method
func (_m *MockRequest) Suspicious() int {
	ret := _m.ctrl.Call(_m, "Suspicious")
	ret0, _ := ret[0].(int)
	return ret0
}

// Suspicious indicates an expected call of Suspicious
func (_mr *MockRequestMockRecorder) Suspicious() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Suspicious")
}

// Timestamp mocks base method
func (_m *MockRequest) Timestamp() time.Time {
	ret := _m.ctrl.Call(_m, "Timestamp")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Timestamp indicates an expected call of Timestamp
func (_mr *MockRequestMockRecorder) Timestamp() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Timestamp")
}

// UserAgent mocks base method
func (_m *MockRequest) UserAgent() string {
	ret := _m.ctrl.Call(_m, "UserAgent")
	ret0, _ := ret[0].(string)
	return ret0
}

// UserAgent indicates an expected call of UserAgent
func (_mr *MockRequestMockRecorder) UserAgent() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "UserAgent")
}
